# Generated by Django 5.2.3 on 2025-06-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='post_mediafiles/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='post_mediafiles/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='post_mediafiles/')),
            ],
        ),
    ]
