# Generated by Django 5.2.3 on 2025-07-13 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_book_post_destination'),
        ('reviews', '0002_review_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='book_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.review'),
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
