# Generated by Django 5.2.3 on 2025-07-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_book_review_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.ImageField(default=3, upload_to='post_mediafiles/'),
            preserve_default=False,
        ),
    ]
