# Generated by Django 5.2.3 on 2025-07-18 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_destinations'),
        ('destinations', '0001_initial'),
        ('posts', '0004_alter_post_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
        migrations.AlterField(
            model_name='post',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinations.destination'),
        ),
    ]
