# Generated by Django 5.2.3 on 2025-07-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='destinations',
            field=models.ManyToManyField(related_name='books', to='destinations.destination'),
        ),
    ]
