# Generated by Django 5.2.3 on 2025-07-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_destinations'),
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='destinations',
            field=models.ManyToManyField(blank=True, related_name='books', to='destinations.destination'),
        ),
    ]
