# Generated by Django 5.2.3 on 2025-07-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
