# Generated by Django 5.2.3 on 2025-07-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_bio_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
