# Generated by Django 5.2.3 on 2025-07-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_bio_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio_info',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
